[2024-02-27T16:51:56.567+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_run.print_dag_run scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-02-27T16:51:56.573+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_run.print_dag_run scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-02-27T16:51:56.574+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 3
[2024-02-27T16:51:56.583+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): print_dag_run> on 2024-01-01 00:00:00+00:00
[2024-02-27T16:51:56.587+0000] {standard_task_runner.py:60} INFO - Started process 646 to run task
[2024-02-27T16:51:56.588+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_run', 'print_dag_run', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/dag_run.py', '--cfg-path', '/tmp/tmpyj7skneb']
[2024-02-27T16:51:56.590+0000] {standard_task_runner.py:88} INFO - Job 53: Subtask print_dag_run
[2024-02-27T16:51:56.674+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_run.print_dag_run scheduled__2024-01-01T00:00:00+00:00 [running]> on host 1927bc465fbc
[2024-02-27T16:51:56.801+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='vutt' AIRFLOW_CTX_DAG_ID='dag_run' AIRFLOW_CTX_TASK_ID='print_dag_run' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2024-02-27T16:51:56.803+0000] {logging_mixin.py:188} INFO - 2024-02-27 16:51:56.194134+00:00
[2024-02-27T16:51:56.803+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-02-27T16:51:56.826+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=dag_run, task_id=print_dag_run, execution_date=20240101T000000, start_date=20240227T165156, end_date=20240227T165156
[2024-02-27T16:51:56.882+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-27T16:51:56.924+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
